version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  commands:
    - pip install .[doc]
    - cat docs/conf.py
    - python -m sphinx -T -E -b html -d _readthedocs/doctrees -D language=en docs _readthedocs/html
