name: Bug reports for commands
description: For bugs that involve commands found within Red.
title: ''
labels: 'Type: Bug'
assignees: ''
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out an issue. This template is meant for any issues related to commands.
      If you require help with installing Red we ask that you join our [Discord server](https://discord.gg/red)
- type: input
  id: red-version
  attributes:
    label: "What Red version are you using?"
    placeholder: 3.4.5
  validations:
    required: true
- type: dropdown
  id: cog-name
  attributes:
    label: "Cog name"
    description: "From which cog does the command come from?"
    options:
      - Admin
      - Alias
      - Audio
      - Bank
      - Cleanup
      - CogManagerUI
      - Core
      - Customcom
      - Dev
      - Downloader
      - Economy
      - Filter
      - General
      - Image
      - Mod
      - Modlog
      - Mutes
      - Permissions
      - Reports
      - Streams
      - Trivia
      - Warnings
  validations:
    required: true
- type: input
  id: command-name
  attributes:
    label: "Command name"
    description: "What is the command that caused the error?"
    placeholder: "play"
  validations:
    required: true
- type: textarea
  id: weh
  attributes:
    label: "What did you expect to happen?"
  validations:
    required: true
- type: textarea
  id: wah
  attributes:
    label: "What actually happened?"
    description: |
      A clear and concise description of what the bug is.
      If the issue is visual in nature, consider posting a screenshot.
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: "How can we reproduce this error?"
    description: "List of steps required to reproduce this error."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: Let us know if you have anything else to share.
