CASETYPES = [
    {
        "name": "ban",
        "default_setting": True,
        "image": "\N{HAMMER}",
        "case_str": "Ban",
        "audit_type": "ban",
    },
    {
        "name": "kick",
        "default_setting": True,
        "image": "\N{WOMANS BOOTS}",
        "case_str": "Kick",
        "audit_type": "kick",
    },
    {
        "name": "hackban",
        "default_setting": True,
        "image": "\N{BUST IN SILHOUETTE}\N{HAMMER}",
        "case_str": "Hackban",
        "audit_type": "ban",
    },
    {
        "name": "tempban",
        "default_setting": True,
        "image": "\N{ALARM CLOCK}\N{HAMMER}",
        "case_str": "Tempban",
        "audit_type": "ban",
    },
    {
        "name": "softban",
        "default_setting": True,
        "image": "\N{DASH SYMBOL}\N{HAMMER}",
        "case_str": "Softban",
        "audit_type": "ban",
    },
    {
        "name": "unban",
        "default_setting": True,
        "image": "\N{DOVE OF PEACE}",
        "case_str": "Unban",
        "audit_type": "unban",
    },
    {
        "name": "voiceban",
        "default_setting": True,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Voice Ban",
        "audit_type": "member_update",
    },
    {
        "name": "voiceunban",
        "default_setting": True,
        "image": "\N{SPEAKER}",
        "case_str": "Voice Unban",
        "audit_type": "member_update",
    },
    {
        "name": "vmute",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Voice Mute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "cmute",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Channel Mute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "smute",
        "default_setting": True,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Server Mute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "vunmute",
        "default_setting": False,
        "image": "\N{SPEAKER}",
        "case_str": "Voice Unmute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "cunmute",
        "default_setting": False,
        "image": "\N{SPEAKER}",
        "case_str": "Channel Unmute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "sunmute",
        "default_setting": True,
        "image": "\N{SPEAKER}",
        "case_str": "Server Unmute",
        "audit_type": "overwrite_update",
    },
    {
        "name": "vkick",
        "default_setting": False,
        "image": "\N{SPEAKER WITH CANCELLATION STROKE}",
        "case_str": "Voice Kick",
    },
]
