libs =
#import libs += libhello%lib{hello}


import libs += sol2%lib{sol2}


# File system included libs
import libs += libdpp%lib{dpp}



exe{Aurora}: {hxx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"
