from random import choice as randchoice
from discord.ext import commands

bcode = {
    1: 'THE GOLDEN RULE (Article 1):Bros before hoes. Always remember, girlfriends come and go, but your boys are always there. Breaking this rule is to commit the cardinal sin against Team Testosterone.',
    2: 'A Bro is always entitled to do something stupid, as long as the rest of his Bros are doing it.',
    3: 'If a Bro gets a dog, it must be at least as tall as his knee when full-grown.',
    4: 'A Bro never divulges the existence of the Bro Code to a woman. It is a sacred document not to be shared with chicks for any reason...no, not even that reason.',
    5: 'Whether he cares about sports or not, a Bro cares about sports.',
    6: 'A Bro shall not lollygag if he must get naked in front of other Bros in a gym locker room.',
    7: 'A Bro never admits he cant drive stick. Even after an accident.',
    8: 'A Bro never sends a greeting card to another Bro.',
    9: 'Should a Bro lose a body part due to an accident or illness, his fellow Bros will not make lame jokes such as Gimme three! or Wow, quitting your job like that really took a lot of ball. Its still a high five that Bro still has a lot of balls...metaphorically speaking, of course.',
    10: 'A Bro will drop whatever hes doing and rush to help his Bro dump a chick.',
    11: 'A Bro may ask his Bro(s) to help him move, but only after first disclosing an honest estimate on both time commitment and number of large pieces of furniture. If the Bro has vastly underestimated either, his Bros retain the right to leave his possessions where they are-in most cases,stuck in a doorway.',
    12: 'Bros do not share dessert.',
    13: 'All Bros shall dub one of their Bros his wingman.',
    14: 'If a chick inquires about another Bros sexual history, a Bro shall honor the Brode Of Silence and play dumb. Better to have women think all men are stupid than to tell the truth.',
    15: 'A Bro never dances with his hands above his head.',
    16: 'A Bro should be able, at any time, to recite the following reigning champions: Super Bowl, World Series and Playmate of the Year.',
    17: 'A Bro shall be kind and courteous to his co-workers, unless they are beneath him on the Pyramid of Screaming.',
    18: 'If a Bro spearheads a beer run at a party, he is entitle to an excess money accrued after canvassing the group.',
    19: 'A Bro shall not sleep with another Bros sister. However, a Bro shall not get angry if another Bro says Bro, your sister is hot!',
    20: 'A Bro respects his Bros in the military because they have selflessly chosen to defend the nation, but  more to the point, because they can kick his ass six ways to Sunday.',
    21: 'A Bro never shares observations about another Bros smoking-hot girlfriends. Even if the Bro with the hot girlfriend attempts to bait the Bro by sayin, She;s smoking-hot,huh? a Bro shall remain silent, because in this situation, he is the only one who should be baiting.',
    22: 'There is no law that prohibits a woman from being a Bro.',
    23: 'When flipping through TV channels with his Bros, a Bro is not allowed to skip past a program featuring boobs. This includes, but is not limited to, exercise shows, womens athletics, and on some occasions, surgery programs.',
    24: 'When wearing a baseball cap, a Bro may position the brim at either 12 or 6 oclock. All other angles are reserved for rappers and the handicapped.',
    25: 'A Bro does not let another Bro get a tattoo, particularly a tattoo of a girls name.',
    26: 'Unless he has children, a Bro shall not wear his cell phone on a belt clip.',
    27: 'A Bro never removes his shirt in front of other Bros, unless at a resort pool or the beach.',
    28: 'A Bro will, in a timely manner, alert his Bro to the existence of a girl fight.',
    29: 'If two Bros decide to catch a movie together, they may not attend a screening that begins after 4:40PM. Also, despite the cost savings, they shall not split a tub of popcorn, choosing instead to procure individual bags.',
    30: 'A Bro does not comparison shop.',
    31: 'When on the prowl, a Bro hits on the hottest chick first because you just never know.',
    32: 'A Bro does not all another Bro to get married until he is at least thirty.',
    33: 'When in a public restroom, a Bro (1) stares straight ahead when using the urinal; (2) makes the  obligatory comment, What is this, a chicks restroom? If there are more than two dudes waiting to pee; and (3) attempts to shoot his used paper towel into trash can like basketball...rebounding is optional.',
    34: 'Bros cannot make eye contact during a devils threeway. (Two Bros)',
    35: 'A Bro never rents a chick flick.',
    36: 'When questioned in the company of women, a Bro always decries fake breasts.',
    37: 'A Bro is under no obligation to open a door for anyone. If a woman insist on having their own  professional basketball league, then they can open their own doors. Honestly, they are not that heavy.',
    38: 'Even in a fight to the death, a Bro never punches another Bro in the groin.',
    39: 'When a Bro gets a chicks number, he waits at least ninety-six hours before calling her.',
    40: 'Should a Bro become stricken with engagement, his Bros shall stage an intervention and attempt to heal him. This is more commonly know as a bachelor party.',
    41: 'A Bro never cries.   !Exceptions: Watching Field of Dreams, E.T. or a sports legend retires.',
    42: 'Upon greeting another Bro, a Bro may engage in a high five, fist bump, or a Bro hug, but never a full embrace.',
    43: 'A Bro loves his country, unless that country is not America.',
    44: 'A Bro never applies sunscreen to another Bro.',
    45: 'A Bro never wears jeans to a strip club.',
    46: 'If a Bro is seated next to some dude who is stuck in the middle seat on an airplan, he shall yield him all of their shared armrest, unless the dude has (a) taken his shoes off, (b) is snoring, (c) makes the Bro get up more than once to use the lavatory, or (d) purchased headphones after they announced the in-flight movie is 27 Dresses, See articles 35.',
    47: 'A Bro never wears pink. Not even in Europe.',
    48: 'A Bro never publicly reveals how many chicks he or another Bro has banged.',
    49: 'When asked, Do you need some help? a Bro shall automatically respond, I got it, whether or not he is actually got it. !Exceptions: Carrying an expensive TV, parallel parking and expensive car, or loading and expensive TV into an expensive car.',
    50: 'If a Bro should accidentally strike another Bros undercarriage with his arm while walking, both Bros silently agree to continue on as if it never happened.',
    51: 'A Bro checks out another Bros blind date and reports back with a thunbs-up or thumbs-down.',
    52: 'A Bro is not required to remember another Bros birthday, though a phone call every now and again probably would not kill him.',
    53: 'Even in a drought, a Bro flushes twice.',
    54: 'A Bro is required to go out with his Bros on St. Pattys Day and other official Bro holidays, including Halloween, New Years Eve, and Desperation Day (February 13).',
    55: 'Even in an emergency that requires a tourniquet, a Bro never borrows from or lends clothes to another Bro.',
    56: 'A Bro is required to alert another Bro is the Bro/Chick Ratio at a praty falls below 1:1. However, to avoid Broflation, a Bro is only allowed to alert on Bro. Further, a Bro may not speculate on the  anticipated Bro/Chick Ratio of a party or a venue without first disclosing the present-time observed ratio.',
    57: 'A Bro never reveals the score of a sporting event to another Bro unless that Bro has thrice confirmed he wants to hear it.',
    58: 'A Bro does not grow a mustache. !Exceptions: Tom Selleck.',
    59: 'A Bro must always post bail for another Bro, unless it is out of state or, like, crazy expensive.',
    60: 'A Bro shall honor thy father and mother, for they were once Bro and chick. However, a Bro never thinks of them in that capacity.',
    61: 'If a Bro, for whatever reason, becomes aware of another Bros anniversary with a chick, he shall endeavor to make this information available to his Bro, regardless of whether he thinks his Bro already knows.',
    62: 'In the event that two Bros lock on to the same target, the Bro who calls dibs first has dibs. If both  dibs at the same time, the Bro who counts aloud to ten the fastest has dibs. If both arrive at the  number ten at the same time, the Bro who bought the last round of drinks has dibs. If they have not purchased drinks yet, the taller of the two Bros has dibs. If they are the same height, the Bro with the longer dry spell has dibs. Shoudl the dry spells be of equal length, a game os discreet Broshambo shall determine dibs, provided the chick is still there.',
    63: 'A Bro will make any and all efforts to provide his Bro with protection.',
    64: 'A Bro must provide his Bro with a ticket to and event if said event involves the latter Bros favorite sports team in a playoff scenario.',
    65: 'A Bro must always reciprocate a round of drinks among Bros. !Exceptions: A Bro is off the hook if his Bro orders a drink that arrives with an umbrella in it.',
    66: 'If a Bro suffers pain due to the permanent dissolution of a relationship with a lady friend, his Bro shall offer no more than a that sucks,bro and copious quantities of beer. To eliminate the  possibility of any awkward moments in the future, his Bros shall also refrain for any pejorative commentary-deserved or not-regarding said lady friend for a period of three months, when the requisite backslide window has fully closed.',
    67: 'Should a Bro pick up a guitar at a party and commence playing, another Bro shall point out that he is a tool.',
    68: 'If a Bro be on a hot streak, another Bro will do everything possible to ensure its longevity, even if that includes jeopardizing his own personal records, the missing of work, or, if necessary, generating a realistic fear that the end of the world is imminent. !Exceptions: Dry spell trumps hot streak.',
    69: 'Duh.',
    70: 'A Bro will drive another Bro to the airport or pick him up, but never both for the same trip. He is not expected to be on time, help with luggage, or inquire about his Bros trip or general well-being.',
    71: 'As a courtesy to Bros the world over, a Bro never brings more than two other Bros to a party.',
    72: 'A Bro never spell-checks.',
    73: 'When a group of Bros are in a restaurant, each shall engage in the time-honored ritual of jockeying to pay the bill, regardless of affordability. When the group ultimately decides to divide the check, each Bro shal act upset rather than enormously relieved.',
    74: 'At a red light, a Bro inches as close as possible to the rear bumper of the car in front of him, and  immediately honks his horn when the light turns green. That way, if another Bro is several cars behind, he will have a better chance of making it through the intersection before the light turns red again.',
    75: 'A Bro automatically enhances another Bros job description when introducing him to a chick.',
    76: 'If a Bro is on the phone with a chick while in front of his Bros and, for whatever reason, desires to say I love you, he shall first excuse himself from the room or emply a subsonic, Barry White-esque tone.',
    77: 'Bros do not cuddle. !Exceptions: NONE!',
    78: 'A Bro shall never rack jacks his wingman.',
    79: 'At a wedding, Bros shall reluctantly trudge out for the garter toss and feign interest for the benefit of the chicks present. Whichever Bro gets stuck with the garter shall lightheartedly pretend he is not horrified at the thought of being the next one to drop before scurrying to the bar for a very stiff  drink and/or shots.',
    80: 'A Bro shall make every effort to aid another Bro in riding the tricycle, short of completing the tricycle himself.',
    81: 'A Bro leaves the toilet seat up for his Bros.',
    82: 'If two Bros get into a heated argument over something and one says something out of line, the other not expect him to take it back or apologize to make amends. That is inhuman.',
    83: 'A Bro shall, at all costs, honor the Platinum Rule: Never, ever, ever, ever love thy neighbor. In particular, a Bro shall never mix it up romantically with a co-worker. !Exceptions: (1) Co-worker is an eight or better. (2) You are co-workers superior. (3) Co-worker dresses a little slutty. (4) Company recently sued for sexual harassment-unlikely to happen again. (6) You are switching floors soon. (7) You and co-worker get stuck in elevator.',
    84: 'A Bro shall stop whatever he is doing and watch Die Hard, The Shawshank Redemption, Top Gun, The Big Lebowski, the first half of Full Metal Jacket, or porn if it is on TV.',
    85: 'If a Bro buys a new car, he is required to pop the hood when showing it off to his Bros.',
    86: 'When a Bro meets a chick, he shall endeavor to find out where she fits on the Hot/Crazy Scale before pursuing her.',
    87: 'A Bro never questions another Bros stated golf score, maximum bench press, or height. He can, however, ask the Bro to prove it, traditionally in the form of a wager.',
    88: 'If a Bro, for whatever reason, must drive another Bros car, he shall not adjust the preprogrammed radio stations, the mirrors, or the seat position, even if this last requirement results in the Bro trying to drive the vehicle as a giant praying mantis would.',
    89: 'A Bro shall always say yes in support of a Bro.',
    90: 'A Bro shows up at another Bros party with at least one more unit of alcohol than he plans to drink. So if a Bro plans on chugging a six-pack, he shall bring a six-pack plus at least one can of beer. If the party sucks and/or there are too many dude, the Bro is entitled to leave with his alcohol, though etiquette dictates he should wait until nobody is looking.',
    91: 'If a group of Bros suspect that their Bro is trying to give himself a nickname, they shall rally to call him by an adjacent yet more demeaning nickname.',
    92: 'A Bro keeps his booty calls at a safe distance.',
    93: 'Bros do not speak French to one another.',
    94: 'If a Bro is in a bathroom and runs out of toilet paper, another Bro may toss him a new roll, but at no point may their hands touch or the door open more than 30 degrees.',
    95: 'A Bro shall alert another Bro to the presence of a chesty woman, regardless of whether or not he knows the Bro. Such alerts may not be administered verbally.',
    96: 'Bros shall go camping once a year, or at least attempt to start a fire. !Note: Attempt to start a fire outside.',
    97: 'Where a Bro went to college is going to kick his Bros colleges ass all over the field this weekend.',
    98: 'A Bro never lies to his Bros about the hotness of chicks at a given social venue or event.',
    99: 'A Bro never asks for directions when lost.',
    100: 'When pulling up to a stoplight, a Bro lowers his window so that all might enjoy his music selection.',
    101: 'If a Bro asks another Bro to keep a secret, he shall take that secret to his grave. This is what makes them Bros, not chicks.',
    102: 'A Bro shall take great care in selecting and training his wingman.',
    103: 'A Bro never wears socks with sandals. He commits to one cohesive footgear plan and sticks with it.',
    104: 'The mom of a Bro is always off-limits. But the stepmom is a Bro is fair game if she initiates and/or is wearing at least one article of leopard print clothing...provided she looks good in it...but not if she smokes menthol cigarettes.',
    105: 'If a Bro is not invited to another Bros wedding, he does not make a big deal out of it, even if, lets face it, he was kind of responsible for setting up the couple and had already picked out the perfect wedding gift and everything. Its cool. No big whoop.',
    106: 'Given an option on quantity when ordering a beer with his Bros, a Bro always selects the largest size available or shall never hear the end of it that night.',
    107: 'A Bro never leaves another Bro hanging.',
    108: 'If a Bro forgets a guys name, he may call him brah, dude, or man, but never Bro.',
    109: 'When Bros attend a sporting event and see themselves on the JumboTron, they shall purse their lips and flex their biceps while informing the crowd that their team is number one, despite any objective rankings to the contrary.',
    110: 'If a Bro is hitting it off with a chick, his Bro shall do anything within his means to ensure the desired outcome.',
    111: 'If a Bro discovers another Bro has forgotten to sign out of his email, the Bro will sign out for him, but only after first sending a few angry emails to random contacts and then deleting all sent messages.',
    112: 'A Bro does not sing along to music in a bar. !Exception : A Bro may participate in karaoke. !!Exception To Exception: No chick songs.',
    113: 'A Bro abides by the accepted age-diffrence formula when pursuing a younger chick !Formula: x< or = to y/2+7     x= chicks age; y= Bros age',
    114: 'If a Bro must crash on his Bros couch for an extended period of time, he shall offer to split the cost of toilet paper and the cable bill if said period exceeds two weeks. If he stays longer than a month, he shall offer to contribute some rent. If he stays longer than two months, he shall steam clean the couch or have it incinerated, whichever is more applicable.',
    115: 'A clothing optional beach does not really mean clothing optional for Bros.',
    116: 'A Bro shall not kill another Bro or a Bros chances to score with a chick.',
    117: 'A Bro never willingly relinquishes possession of a remote control. If another Bro desires a channel change, he may verbally request one or engage in the fools errand of getting up to manually change the channel.',
    118: 'When a Bro is with his Bros, he is not a vegetarian.',
    119: 'When three Bros must share the backseat of a car, it is unacceptable for any Bro to put his arm around another Bro to increase space. Likewise, it is unacceptable for two Bros to share a motorcycle, unless said motorcycle is equipped with a sidecar...a Brotorcycle.',
    120: 'A Bro always calls another Bro by his last name.',
    121: 'Even if he is never skied before, a Bro does not trifle with the bunny slope.',
    122: 'A Bro is always psyches. Always.',
    123: 'Two Bros shall maintain at least a three-foot radius between them while dancing on the same floor,even when reenacting the knife fight from Beat It, which, I guess, two Bros should not do anyway, or at least not very often.',
    124: 'If a Bro should shoot an air ball, strike out while playing baseball, or throw a gutter ball while Browling, he is required to make some sort of excuse for himself.',
    125: 'If a Bro is driving ahead of another Bro in a Bro Train, he is required to attempt to lose him in traffic as a funny joke.',
    126: 'In a scenario where two or more Bros are watching entertainment of the adult variety, on Bro is  forbidden from intentionally or unintentionally touching another Bro in ANY capacity. This may include but is not limited to: the high-five, the fist bump, or the congratulatory gluteal pat. Winking is also kind of a no-no.',
    127: 'A Bro will always help another Bro reconstruct the events from the previous night, unless those events entail hooking up with an ugly chick or the Bro repeatedly saying I love you, man to all his Bros.',
    128: 'A Bro never wears two articles of clothing at the same time that bear the same school name, vacation destination, or sports team. Even in a laundry emergency, it is preferred that a Bro go out half naked rather than  violate this code...half naked from the waist up, naturally.',
    129: 'If a Bro lends another Bro a DVD, video game, or piece of lawn machinery, he shall not expect to ever get it back, unless his Bro happens to die and bequeath it back to him.',
    130: 'If a Bro learns another Bro has been in a traffic accident, he must first ask what type of car he collided with and whether it got totaled before asking if his Bro is okay.',
    131: 'While a Bro is not expected to know exactly how to change a tire, he is required to at least drag out the jack and stare at the flat for a while. If he needs to consult the cars ownership manual to locate the jack, he shall do so from inside the car, where he is not visible to passerby and where he can discreetly call a tow truck, after which it is recommended that he hide the jack by the side of the road so he will have a legitimate excuse when the tow truck arrives.',
    132: 'If a Bro decides to let all of his Bros down and get married, he is required to invite them to the wedding, even if this directly violates the wishes of his fiancee and results in a no sex penalty or whatever lame domestic punishment couples might employ.',
    133: 'A Bro only claims a fart after first accusing at least one other Bro. !Exception: Pull my finger.',
    134: 'A Bro is entitled to use a woman as his wingman.',
    135: 'If a scenario arises in which a Bro has promised two of his Bros permanent shotgun, one of the following shall determine the copilot: (1) foot race to the car, (2) silent auction, or in the case of a road trip exceeding 450 miles, (3) a no-holds-barred cage match to the death.',
    136: 'When interrogated by a girlfriend about a bachelor party, a Bro shall offer nothing more than an uninterested It was okay.',
    137: 'When hosting, a Bro orders enough pizza for all his Bros. !The Pizza Equation: P=3b/8   p= number of pizzas(rounded up to the nearest integer)   b = number of Bros(including yourself)',
    138: 'A real Bro does not laugh when a guy gets hit in the groin.',
    139: 'Regardless of veracity, a Bro never admits familiarity with a Broadway show or musical, despite the fact that, yes, Broadway begins with Bro.',
    140: 'A Bro reserves the right to simply walk away during the first five minutes of a date. (aka. The Lemon Law)',
    141: 'A Bro can only get a manicure if (a) he is trying to sleep with the hot Asian woman performing the  manicure, or (b) it is been longer than a month since his last manicure. Its called the Bro code, not the Slob Code.',
    142: 'A Bro shall seek no revenge if he passes out around his Bros and wakes up to find marker all over his face.',
    143: 'When executing a high five, a Bro is forbidden from intertwining fingers or grasping his Bros hand.',
    144: 'It is unacceptable for two Bros to share a hotel bed without first exhausting all couch, cot, and pillows-on-floor combinations. If its still unavoidable, they shall prevent and accidental spoonage by arm wrestling to determine who sleeps under the covers. Once decided, each Bro shall don as many lower layers as possible before silently fist bumping the other Bro good night.',
    145: 'A Bro is never offended if another Bro fails to return a phone call, text, or email in a timely fashion.',  
    146: 'A Bro refrains from usuing too much detail when relating sexual exploits to his Bros.',
    147: 'If a Bro sees another Bro get into a fight, he immediately has his Bros back.',
    148: 'A Bro does not listen to chick music...in front of other Bros. When alone, a Bro may listen to,say, a Sarah McLachlan album or two, but only to gain valuable insights into the female psyche, not because he finds her melodies tragically haunting yet curiously uplifting at the same time.',
    149: 'A Bro pretends to understand and enjoy cigars.',
    150: 'No sex with your Bros ex.',
}

class Bcode:
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    async def brocode(self, num: int=None):
        """BroCode Shows the laws that all Bros must obey"""
        if num:
            if num < 0:
                await self.bot.say('LOL SO FUNNY')
                return
            if num > 151:
                await self.bot.say('Take it easy Bro! We dont need that many. A Bro can only remember so many things at a time!')
                return
            await self.bot.say("Article {}: {}".format(num, bcode[num]))
            return
        brocode = randchoice(list(bcode.keys()))
        await self.bot.say("Article {}: {}".format(brocode, bcode[brocode]))

def setup(bot):
    n = Bcode(bot)
    bot.add_cog(n)